apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    {{ .Values.label.key }}: {{ .Values.label.value }}
  ports:
    - protocol: TCP
      port: {{ .Values.port.source }}
      targetPort: {{ .Values.port.target }}